from lcd_display import lcd
from time import sleep

screen = lcd()

screen.clear()
screen.display_string("*                   ", 1)
screen.display_string("*-                  ", 1)
screen.display_string("*--                 ", 1)
screen.display_string("*---                ", 1)
screen.display_string("*----               ", 1)
screen.display_string("*-----              ", 1)
screen.display_string("*------             ", 1)
screen.display_string("*-------            ", 1)
screen.display_string("*--------           ", 1)
screen.display_string("*---------          ", 1)
screen.display_string("*----------         ", 1)
screen.display_string("*-----------        ", 1)
screen.display_string("*------------       ", 1)
screen.display_string("*-------------      ", 1)
screen.display_string("*--------------     ", 1)
screen.display_string("*---------------    ", 1)
screen.display_string("*----------------   ", 1)
screen.display_string("*-----------------  ", 1)
screen.display_string("*------------------ ", 1)
screen.display_string("*------------------*", 1)
screen.display_string("                   |", 2)
screen.display_string("                   |", 3)
screen.display_string("                   *", 4)
screen.display_string("                  -*", 4)
screen.display_string("                 --*", 4)
screen.display_string("                ---*", 4)
screen.display_string("               ----*", 4)
screen.display_string("              -----*", 4)
screen.display_string("             ------*", 4)
screen.display_string("            -------*", 4)
screen.display_string("           --------*", 4)
screen.display_string("          ---------*", 4)
screen.display_string("         ----------*", 4)
screen.display_string("        -----------*", 4)
screen.display_string("       ------------*", 4)
screen.display_string("      -------------*", 4)
screen.display_string("     --------------*", 4)
screen.display_string("    ---------------*", 4)
screen.display_string("   ----------------*", 4)
screen.display_string("  -----------------*", 4)
screen.display_string(" ------------------*", 4)
screen.display_string("*------------------*", 4)
screen.display_string("|                  |", 3)
screen.display_string("|                  |", 2)
screen.display_string("|   I  LOVE  YOU   |", 2)
sleep(1)
screen.display_string("|    so  much!!    |", 3)
sleep(1.5)
screen.display_string("|  Anna & Adrian   |", 2)
screen.display_string("|     FOREVER      |", 3)

sleep(3)

screen.clear()

